### ISSUE TITLE
file->sync:  zero-length file does not overwrite previous content

### ISSUE THREAD

**Issue by jtfrey** [warewulf/warewulf3#124]
In the sync() subroutine of common/lib/Warewulf/File.pm, once the new content has been read from the origin the loop to add the new content to the data store looks like this:

```
my $was_stored = 1;

while ($total_len > $cur_len) {
  :
}
if ( $was_stored ) {
  $self->checksum($digest->hexdigest());
  $self->size($total_len);
  $db->persist($self);
```

So if $total_len is zero, the loop is never entered and the previous content remains in the data store.  Despite that fact, $was_stored goes ahead and updates the checksum and size and persists the file object.

I noticed this because the file.pl CGI was dumping a lot of messages about a file whose cached copy didn't match the persisted checksum.  A "wwsh file show .." demonstrated that while the object showed length 0, the old content was still being pulled from the data store.

**Comment by jtfrey** [comment]
See pull request #125

**Comment by bensallen** [comment]
#125 merged. Closing.
