### ISSUE TITLE
add lan channel to ipmi configuration

### ISSUE THREAD

**Issue by renatopancheri** [warewulf/warewulf3#158]
I need the ability to set the lan channel for the ipmi/initramfs/10-ipmiconfig script,
i saw that it already looks for a variable named WWIPMI_LANCHANNEL that is not set anywhere tho:
https://github.com/warewulf/warewulf3/blob/fea4d17ad8e8ce98e28e16cd290b7d206acf1309/ipmi/initramfs/10-ipmiconfig#L34
I added the option to set this using wwsh ipmi:

>  [root@boot-ctn vendor_perl]# wwsh ipmi set n0005 --lanchannel=3
>Are you sure you want to make the following changes to 1 node(s):
>
>     SET: IPMI_LANCHANNEL     
>
>Yes/No> Yes

As far as i tested it works without problems, if you are interested in this i can send you a patch or a pull request, just let me know.

**Comment by bensallen** [comment]
Hi @renatopancheri,

Good job finding one of Warewulf's hidden settings. One can set this and other settings found in the initramfs "by hand" via `wwsh object modify -s IPMI_LANCHANNEL=3 n0005`

A patch would be awesome to add this setting into the ipmi CLI.

Thanks!

**Comment by renatopancheri** [comment]
Here is a patch, if you want me to change something / make a pull request just let me know.
[lan_channel.txt](https://github.com/warewulf/warewulf3/files/2528787/lan_channel.txt)

**Comment by bensallen** [comment]
Looks fine. Can you make a pull request against the development branch with this change?

**Comment by renatopancheri** [comment]
i will tomorrow
