### ISSUE TITLE
libarchive

### ISSUE THREAD

**Issue by mdidomenico4** [warewulf/warewulf3#167]
Is there a reason the libarchive source tar is being included in the git repo?  my av scanners are not allowing me to clone the repo because of provision/3rd_party/bsd/libarchive.  the scanner complains about password protected files in the archive which it can't scan.

**Comment by jmstover** [comment]
We use bsdtar from libarchive in the bootstrap we build. What files are being complained about?

The only non-text files in the archive are PDF files, and the PDF files are just PDF's of the man pages. None are password protected.

**Comment by mdidomenico4** [comment]
in the test directories there are a bunch of uuencoded files, when you uudecode them, they turn into zip or others that require a passphrase.  i fully suspect there's nothing nefarious going on, but it triggers an AV alert on me and i can't pull in the data.

**Comment by bensallen** [comment]
Compared to Busybox's tar, libarchive's bsdtar is capable preserving xattrs, which is necessary for images using selinux and Linux capabilities.

libarchive-3.3.1.tar.gz comes directly from https://libarchive.org/downloads/.

**Comment by mdidomenico4** [comment]
sorry my less then clear initial report, failed to question;  what is the repercussion to the build system if that archive were to be excluded from the checkout?  will i still be able to build warewulf?  it looks like libarchive comes with redhat 7.6, is that version sufficient for building?

**Comment by jmstover** [comment]
The build will fail as is. If you look at:  `provision/initramfs/Makefile.am` you will see where it's being used.

If you want to build without the provided libarchive ... you'd need to be sure you have a **static** build of bsdtar available to you, then in the `provision/initramfs/Makefile.am` file:

*) Remove `libarchive` from the `rootfs` target.
*) In the `rootfs` target, find the:
```
if [ -n "@local_libarchive_path@" -a [...]
```
`if` block, and replace that entire block with a copy of the host **static** bsdtar to `rootfs/bin/bsdtar`

... Then from `provision/` run `./autogen.sh` again to regenerate the files.

It can be built without the provided libarchive, you just need to be sure you have the actual requirements available to you to use.

**Comment by bensallen** [comment]
Also if you wanted to use the development branch, the SUSE folks added --with-local-* ./configure options for the various 3rd party software in provision. We're not doing anything special with the bsdtar compile: https://github.com/warewulf/warewulf3/blob/development/provision/initramfs/Makefile.am#L22

**Comment by mdidomenico4** [comment]
This can be closed, thanks for the help.
