### ISSUE TITLE
Stateful provisioning to NVME devices

### ISSUE THREAD

**Issue by jabl** [warewulf/warewulf3#169]
Trying to partition a NVME device fails, in /var/log/warewulf/provision/filesystems.log  on can see

<pre><code>+ msg_gray    * formatting /dev/nvme0n11
+ echo -ne \033[1;30m
+ echo -ne    * formatting /dev/nvme0n11
+ echo -ne \033[0;39m
+ /sbin/mkswap /dev/nvme0n11
+ wwfailure
+ echo -en \033[75G
+ msg_red ERROR\n
+ echo -ne \033[1;31m
+ echo -ne ERROR\n
+ echo -ne \033[0;39m
+ exit 2
</code></pre>

The problem is that partitions on NVME devices are not named by appending the partition index to the device name. In this case, the device is /dev/nvme0n1, but the first partition is named /dev/nvme0n1p1.

That is, for NVME partitions are named by appending 'pN' to the device name.

**Comment by bensallen** [comment]
@jabl Try something along the lines from this example:

```
select /dev/nvme0n1
mklabel gpt
mkpart primary ext4 1MiB 100%
mkfs p1 ext4 -L nvme0
fstab p1 /nvme0 ext4 defaults 0 0

select /dev/nvme1n1
mklabel gpt
mkpart primary ext4 1MiB 100%
mkfs p1 ext4 -L nvme1
fstab p1 /nvme1 ext4 defaults 0 0
```

**Comment by jabl** [comment]
Thanks a lot, that works!
