### ISSUE TITLE
Software raid (mdadm)

### ISSUE THREAD

**Issue by jabl** [warewulf/warewulf3#177]
For compute nodes with multiple disks, it would be useful to have the capability to combine them into a software raid array with mdadm.

**Comment by bensallen** [comment]
If anyone is interested in this implementing this I can give guidance, but I don't currently have time todo it myself.

mdadm tooling is also GPLv2, so we'll need the author's sign off before we can include it in the project.

**Comment by antanasb** [comment]
Hello Ben, I'm right now in the situation of necessity of mdadm. There is an enclosure of blades each of them having couple of SSD's which are not very reliable. RAID1 could be a good hedging. Could you please give some directions to add mdadm to the bootstrap? Thank you in advance.

**Comment by bensallen** [comment]
@antanasb

A new Makefile.am target here to build mdadm or conditionally pull it from the local system on build: https://github.com/warewulf/warewulf3/blob/development/provision/initramfs/Makefile.am

The rootfs target needs to be updated appropriately as well.

Source goes here and Makefile.am needs to be updated to include the new tar file: https://github.com/warewulf/warewulf3/tree/development/provision/3rd_party/GPL.

An update to https://github.com/warewulf/warewulf3/blob/development/provision/configure.ac#L161 to find a local mdadm.

Then you’ll need to extend https://github.com/warewulf/warewulf3/blob/development/provision/initramfs/capabilities/setup-filesystems/20-filesystems to take new syntax around mdadm and actually setup the arrays appropriately.

Update https://github.com/warewulf/warewulf3/blob/development/provision/lib/Warewulf/Provision.pm#L551, to allow for the new syntax. The number value is the expected number of arguments. This will allow the cli to load the new syntax from a Filesystem config file, /etc/warewulf/filesystem/.

**Comment by antanasb** [comment]
@bensallen 
Hi Ben,
thank you for extending the code and providing directions. 
After solving some urgent tasks I'll try it and will report about results.

**Comment by bensallen** [comment]
This is finally closed via #296.
