### ISSUE TITLE
 wget to add repository is throwing an "404" error on CentOS 7.6-1810 

### ISSUE THREAD

**Issue by H4gb4ard** [warewulf/warewulf3#180]
Hello,

I am trying to add the warewulf repository to CentOS 7.6-1810.

Command used:

_wget_ _-O_ _/etc/yum.repos.d/warewulf-rhel6.repo_ _http://warewulf.lbl.gov/downloads/repo/warewulf-rhel6.repo_

it is failing with a "404: not found" error. 

Could somebody point me to where i can find the repository (preferably compatible to centos/rhel7)?

Any help would be much appreciated.

**Comment by H4gb4ard** [comment]
I'm trying to follow the official installation guide on:

http://warewulf.lbl.gov/recipes/setup/installation

**Comment by jmstover** [comment]
We no longer have a binary RPM distributed. If you clone from git, you can build as the RPM was built like:

```
cd common/
./autogen
./configure --prefix=/usr --localstatedir=/var --sysconfdir=/etc
make && make test
sudo make install
```
The `make test` on common is semi-important to verify. You will probably want to be sure you have the perl CGI module installed. I'm pretty sure RHEL already has ran `h2ph` for building out the `.ph` files needed. If for some reason you get an error like:
```
Can't locate sys/ioctl.ph in @INC [...]
```
You will need to run:
```
cd /usr/include
sudo h2ph -al * sys/*
```

`common` must be the first built/installed. Others depend on things from it.

If you really want a RPM, you can do:
```
cd common/
./autogen && ./configure
make dist
rpmbuild -tb warewulf-common*.tar.gz
```

After the `make dist`, you should have a `warewulf-[name]-[ver].tar.gz` file you can run `rpmbuild` on

**Comment by H4gb4ard** [comment]
Thank you!
