### ISSUE TITLE
wwlivesync breaks /dev/null

### ISSUE THREAD

**Issue by thePinochleKid** [warewulf/warewulf3#193]
I am running warewulf on OpenHPC 1.3.7 and CentOS 7.6

I have encountered an issue that when I run `wwlivesync` on a node, the `/dev/null` file is replaced with a regular file on compute nodes and this causes a lot of problems.  

In order to fix this, I created `/dev/null` manually in the vnfs image using the `mknod -m 0666 /dev/null c 1 3` command. I then ran `wwvnfs` on the chroot, and then ran `wwlivesync` and the file was fixed.  Any changes in the `wwvnfs` can be uploaded without further issues. 

Joey

**Comment by jmstover** [comment]
Look in the VNFS source directory ... so something like:
```
ls -l $VNFS/dev/null
```

Some things (I think yum is guilty here), create an empty `/dev/null` file when they run and one doesn't exist.

So, live sync drops that empty file down on top of the character device.

The VNFS chroot directory _should_ have an empty `/dev` structure. IIRC, we're putting a devtmpfs mount in place.

**Comment by thePinochleKid** [comment]
Is it possible to add the `mknod` command to the centos7 template so that there will be a real dev null in the chroot?

**Comment by jmstover** [comment]
The `$VNFS/dev/` directory should be empty. But _something_ is creating an empty `null` file. When you run `wwlivesync`, you're copying down that empty `null` file (as it probably got caught when you ran `wwvnfs`).

So... There shouldn't be anything in the chroot `dev/` directory.

**Comment by bensallen** [comment]
Should be fixed in #255
