### ISSUE TITLE
bootstrap filesystem failing cause /dev/sd* not ready

### ISSUE THREAD

**Issue by renatopancheri** [warewulf/warewulf3#198]
Hi,

i encountered on some machines a weird issue,
the filesystem script at boot fails with the error:

>  /usr/sbin/parted --align=optimal --script /dev/sda mklabel gpt mkpart primary linux-swap 0% 20% mkpart primary ext4 20% 100% name 1 swap name 2 scratch
Error: Could not stat device /dev/sda - No such file or directory.

the disk is actually present and functioning correctly once the machine has finished booting,
see this:
> [root@n0170 ~]# dmesg|grep -i sda
[    9.481470] sd 6:0:0:0: [sda] 1953525168 512-byte logical blocks: (1.00 TB/931 GiB)
[    9.481878] sd 6:0:0:0: [sda] Write Protect is off
[    9.481885] sd 6:0:0:0: [sda] Mode Sense: 00 3a 00 00
[    9.482094] sd 6:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    9.523815]  sda: sda1 sda2
[    9.524854] sd 6:0:0:0: [sda] Attached SCSI disk

it seems that the filesystem script is called before the kernel adds /dev/sda to the device tree.
The solution i've come up is to create and adhoc pre script to wait for /dev/sda to be ready.
Anyone else has a better idea on how to better handle this situation?

**Comment by bensallen** [comment]
One possible workaround is adding whatever kernel module is being used the controller of sda to `wwkmods=<mod>` in kargs for the host. These are loaded slightly sooner in the boot process compared to when the detect script iterates the PCI bus looking for drivers to load.

Otherwise, we'll probably need to add a check for the device and add a retry mechanism when the 'select sda' is specified: https://github.com/warewulf/warewulf3/blob/development/provision/initramfs/capabilities/setup-filesystems/20-filesystems#L161.

**Comment by renatopancheri** [comment]
Hi, I've finally found the time to look into this thing and i added a check in the 20-filesystems file:
`206,214d205`
`<       if [ "${SELECT_DISK##*/dev/*}" == "" ] && [ ! -b ${SELECT_DISK} ]; then`
`<         msg_gray "   * ${SELECT_DISK} not ready, waiting 5 seconds..."`
`<         sleep 5`
`<         wwsuccess`
`<         if [ ! -b ${SELECT_DISK} ]; then`
`<           wwlogger "Disk: ${SELECT_DISK} not found!"`
`<           exit 2`
`<         fi`
`<       fi`
`267c258,287`

The `${SELECT_DISK##*/dev/*}` is so that this thing is not applied on "select tmpfs"

On the console now i see:

* filesystems                                                          RUNNING
   * mounting /                                                              OK
   * /dev/sda not ready, waiting 5 seconds...                                OK
   * running parted on /dev/sda                                              OK
* formatting /dev/sda1                                                       OK
   * formatting /dev/sda2                                                    OK
   * mounting swap                                                      SKIPPED
   * mounting /scratch                                                       OK
 * filesystems                                                               OK
...

I have put a single check and a sleep of 5 seconds, what do you think its the best thing to do?

P.S. once we are happy with the solution i will make a pull request of course

**Comment by bensallen** [comment]
@renatopancheri I think we should loop over the `[ ! -b ${SELECT_DISK} ]` test for say 5 times, with a sleep 1. Something like:

```
WWSELECTDISKWAIT=${WWSELECTDISKWAIT:=5}

...

local SELECT_RETRY=0

if [ "${SELECT_DISK##*/dev/*}" == "" ]; then

  while [ ! -b "${SELECT_DISK}" ]; do
    if [ "${SELECT_RETRY}" -lt "${WWSELECTDISKWAIT}" ]; then 
      msg_gray " * ${SELECT_DISK} not ready, retrying..."
      SELECT_RETRY="$((SELECT_RETRY+1))"
      sleep 1
    else
      wwfailure
      wwlogger "Disk: ${SELECT_DISK} not found!"
      exit 2
    fi
  done
fi
```

`WWSELECTDISKWAIT=${WWSELECTDISKWAIT:=5}`, lets us override the value via `wwsh object set ...`.

**Comment by renatopancheri** [comment]
@bensallen There were a couple of problems:
1) we are not inside a function but only inside {} so `local` does not work, removed.
2) seems like `[ "${SELECT_DISK##*/dev/*}" == "" ]` works on bash but not on sh, changed in 
`[ -z "${SELECT_DISK##*/dev/*}" ]`
3) fixed prints indentation and stuff like that, final code:

        if [ -z "${SELECT_DISK##*/dev/*}" ]; then
          while [ ! -b "${SELECT_DISK}" ]; do
            if [ "${SELECT_RETRY}" -lt "${WWSELECTDISKWAIT}" ]; then 
              if [ "${SELECT_RETRY}" -eq 0 ]; then
                msg_gray "   * ${SELECT_DISK} not ready, retrying."
              else
                msg_gray "."
              fi
              SELECT_RETRY="$((SELECT_RETRY+1))"
              sleep 1
            else
              wwlogger "Disk: ${SELECT_DISK} not found!"
              exit 2
            fi
          done
          if [ "${SELECT_RETRY}" -gt 0 ]; then
            wwsuccess
          fi
        fi

last if + wwsuccess means if we entered the while loop it means we have printed "disk not ready, retrying..." so i print an "OK" with wwsuccess, if we never entered the loop than we dont print anything.
I need to double check this code, i will write you in the next days but i think it works now.

**Comment by renatopancheri** [comment]
Tested this code on:

1. a node that does not have the /dev/sda problem, works as before
2. setting a block device that does not exists (/dev/sdb), waits 5 sec and prints FAILED, then proceeds with downloading vnfs
3. node with the /dev/sda problem, now it works! here is output of warewulf:

        network initialization files: (eth0)                                OK
        Trying to reach the master node at 10.150.255.252                            OK
        Probing for HW Address: (c4:54:44:80:02:32)                                  OK
        Starting syslogd:                                                            OK
        Getting base node configuration:                                             OK
        Starting the provision handler: 
         * adhoc-pre                                                                 OK
         * ipmiconfig Auto configuration not activated                          SKIPPED
         * filesystems                                                          RUNNING
           * mounting /                                                              OK
           * /dev/sda not ready, retrying.                                           OK
           * running parted on /dev/sda                                              OK
           * formatting /dev/sda1                                                    OK
           * formatting /dev/sda2                                                    OK
           * mounting swap                                                      SKIPPED
           * mounting /scratch                                                       OK
         * filesystems                                                               OK
         * getvnfs                                                              RUNNING
           * fetching centos7.5 (ID:114)                                             OK
           * extracting                                                              OK
           * checksum 6718532dcfa855e2ea2eec2e8dd78950                          SKIPPED
         * getvnfs                                                                   OK
         * config                                                                    OK
         * runtimesupport                                                            OK
         * devtree                                                                   OK
         * kernelmodules                                                             OK
         * files                                                                     OK
         * mkbootable                                                           SKIPPED
         * adhoc-post                                                                OK
         * selinux 
        ...

Should i make a pull request?

**Comment by bensallen** [comment]
Awesome. Yes please do open a PR against the development branch. Thanks.

**Comment by renatopancheri** [comment]
@bensallen I think we can close the issue now!
