### ISSUE TITLE
Create Debian chroot on a CentOS system?

### ISSUE THREAD

**Issue by dawzon** [warewulf/warewulf3#212]
I'm trying to use wwmkchroot with the debian-8 template on a CentOS 7 system (i.e. I'd like to provision some Debian nodes from a CentOS server).    The only [page in the docs](http://warewulf.lbl.gov/recipes/provisioning/debian.html) that I found relating to this assumes that the master system is running Debian.  I briefly tried to get it to work by installing dpkg and deboostrap, but I wasn't able to get wwmkchroot to complete sucessfully.

Is what I'm trying to do even supported?

**Comment by bensallen** [comment]
Hi @dawzon, this isn't something I believe we've tested or ever tried to make work.
