### ISSUE TITLE
cluster-env doesn't check permissions before trying to edit authorized_keys

### ISSUE THREAD

**Issue by solj** [warewulf/warewulf3#216]
My authorized_keys file is set to 400 and every time I try to login, cluster-env tries to write to the file unsuccessfully. I'm not sure what the *right* solution is but perhaps a suggestion to the user to add the appropriate lines would be better than just repeatedly failing.

$ ls -l /home/solj/.ssh/authorized_keys
-rw-------. 1 solj admin 192 Jan 31 13:19 /home/solj/.ssh/authorized_keys

/usr/bin/cluster-env: line 21: /home/solj/.ssh/authorized_keys: Permission denied

**Comment by jmstover** [comment]
`authorized_keys` is set 600 in your output (i.e. you have write access)... is that a modified permission (probably from `cluster-env`)? 

What version of Warewulf are you running? And how did you install it (i.e. OpenHPC? Source?)?

**Comment by jmstover** [comment]
PR #217 _should_ fix getting the error message. Maybe not how you're wanting though...

**Comment by jmstover** [comment]
Hrmm... this should have been autoclosed when #217 was merged... Meh.
