### ISSUE TITLE
Possible libparted link issue

### ISSUE THREAD

**Issue by jmstover** [warewulf/warewulf3#218]
See this thread:
https://groups.google.com/a/lbl.gov/d/msg/warewulf/20-oozEUZSs/Y3d3xPnSAQAJ

libparted.so.2 not being found under /usr/lib location. Linking from /lib64 worked.

**Comment by jmstover** [comment]
@bensallen ... Don't know if you saw the thread.

**Comment by bensallen** [comment]
Fixed in #272.
