### ISSUE TITLE
Validate and update BuildRequires and Requires in specfiles

### ISSUE THREAD

**Issue by jcsiadal** [warewulf/warewulf3#222]
@NaohiroTamura commented on a missing BuildRequires for bsdtar in one of the RPM specs. I've confirmed that and other missing Requires using a pristine mock environment.

Build each SRPM in a bare minimum environment, reset the chroot, and install the resulting RPM. Update *Requires(*) tags to remove errors. Need to do this for CentOS7.7 and 8.1, and SLE12SP5 and LEAP 15.1.

**Comment by jcsiadal** [comment]
Can you assign this to me?

**Comment by bensallen** [comment]
This was added in https://github.com/warewulf/warewulf3/pull/254.
