### ISSUE TITLE
Statefull on Centos8.2/openhpc2.x is not working

### ISSUE THREAD

**Issue by cjcawley** [warewulf/warewulf3#268]
Greetings,

I am getting a wwfailure right after the mkfs and not much else.
It looks like the drive partitions; however, sda2 on shows ext4.

Any help is appreciated.

Thanks
Chris Cawley

**Comment by RexPowerSorcerer** [comment]
Hello, I'm experiencing the same problem, which I will further describe for posterity.

The OpenHPC recipe (Install_guide-Centos8-Warewulf-SLURM-2.0-x86_64.pdf) dictates to duplicate the Warewulf example file directly (efi.cmds in my case). The boot and swap partitions  are created and formatted without any issue, but it seems that the root (ext4) partition fails to format. I've used a GParted Live USB to diagnose what's happening, and it seems that the partition (/dev/sda3 if the example cmds file is used as-is) is indeed created, but not formatted.

Changing the FS key in the provision settings to use ext3 did not help.

After digging through the mailing lists I was inspired to open a pre-shell and was able to isolate the problem to the line in /warewulf/provision/20-filesystems which summons mkfs.ext4. For a reason I wasn't able to understand, mkfs fails to format sda3 to ext4. 

I was able to get an ext2 partition successfully by changing that line to `/sbin/mke2fs -F -L root "$DEV" > [rest of the line]`. Then, runnning the command sh -x /warewulf/provision/20-filesystems had the script successfully complete, and yielded a working ext2-formatted partition, which, I recognize, isn't optimal. Unfortunately that doesn't fix the underlying issue, and would require hand-formatting every node, which I refuse to do. I'm a chemist, not a sys admin.

My hypothesis is that there could be a missing library somewhere, but I am unqualified to verify this, or to add that library myself.

Seeing your original post is almost a month old, let me know if you found a solution to stateful provisoning with the OHPC recipe.

**Comment by cjcawley** [comment]
Apparently , there is a fix from John.
I am in the process of testing it.  It involves downgrading to centos 8.1 for the kernel bootstrap

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by RexPowerSorcerer** [comment]
That's good news! I'll be on the watch for that.

Thank you for letting me know,

-Rex

**Comment by jehane** [comment]
I also have several nodes I need to use in statefull mode and who are touched by this issue. Do you know when the fix will be available ? 

Regards 
Marianne

**Comment by RexPowerSorcerer** [comment]
Unfortunately I haven't found a solution or patch yet, and I'm running
stateless with my software network-mounted.

**Comment by ECoulter** [comment]
The fix here:
https://groups.io/g/OpenHPC-users/message/3900

has worked for me. Short version is that the 'base' bootstrap image is missing a config file needed by mke2fs.

**Comment by bensallen** [comment]
The patch in OpenHPC has been merged in via https://github.com/warewulf/warewulf3/commit/a212d2802855803dabd3fc40d3e16c2c63f77cd1, with a small typo fix in https://github.com/warewulf/warewulf3/commit/ce3b70074ca58ab8dba4b1c95ea2039a2caa79f7.
