### ISSUE TITLE
Hybrid filesystem example

### ISSUE THREAD

**Issue by LecrisUT** [warewulf/warewulf3#270]
I'm trying to implement a hybrid file system according to the [provided example file](https://github.com/warewulf/warewulf3/blob/master/provision/etc/filesystem/examples/hybrid_example.cmds). That part is pretty straightforward, however I would like to have the disk formatted only once, rather than each time the node is restarted. Are there any hints on how to set that up?

**Comment by bensallen** [comment]
After your node's first boot where it's formatted the local disk, update the example to something like:

```# Tmpfs root (equivalent to 20-filesystems' default settings)
select tmpfs
fstab "" / tmpfs rw:relatime:mode=555 0 0

select /dev/sda

# fstab NUMBER fs_file fs_vfstype fs_mntops fs_freq fs_passno
fstab 1 swap swap defaults 0 0
fstab 2 /tmp ext4 rw:relatime:seclabel:nosuid:noexec 0 0
fstab 3 /var ext4 defaults 0 0
```
