### ISSUE TITLE
How do I add lines to dhcp configuration for each node?

### ISSUE THREAD

**Issue by tdunn3-uco** [warewulf/warewulf3#295]
I'm working on booting over infiniband with ipxe and warewulf and I have worked through every bug except one. Warewulf uses the 64bit guid while ipxe passes the 48 bit mac as the Client-Ethernet-Address. I can use GUID Option 97 from the http request but I need to be able to decide how the dhcp file is generated for each node not just adding lines to the top of the dhcpd-template. Where do I do this?

**Comment by jmstover** [comment]
The Node DHCP entries are generated at:
https://github.com/warewulf/warewulf3/blob/f13a37796c333069a7c9e08aa0b00c0643cf3ee0/provision/lib/Warewulf/Provision/Dhcp/Isc.pm#L144

**Comment by tdunn3-uco** [comment]
That's it! Thank you. I can't tell you how long I've been trying to figure this out. The perl module was a little hard to track down on my system but I found it and editing it does the trick. Thanks again.
