### ISSUE TITLE
Print Checksum of VNFS to Console and Syslog for Validation

### ISSUE THREAD

**Issue by bensallen** [warewulf/warewulf3#36]
Allow an easy method of validating the VNFS configured for a node is indeed the VNFS that was provisioned. A quick first pass at this is simply printing the checksum of the VNFS thats stored in the database to the console/syslog in getvnfs.

**Comment by gmkurtzer** [comment]
You can also use the DB last updated on date.

**Comment by bensallen** [comment]
Looking at how we can validate the md5sum of the VNFS in wwgetvnfs. Can anyone think of a better (but still posix compliant) way to stream the VNFS download to gunzip and md5sum in parallel than:

```
mkfifo /tmp/vnfs-download
mkfifo /tmp/vnfs-checksum
mkfifo /tmp/vnfs-extract

WWINIT_HWADDR=08:00:27:9b:39:94
master=127.0.0.1

cat /tmp/vnfs-download | tee /tmp/vnfs-extract > /tmp/vnfs-checksum &
gunzip < /tmp/vnfs-extract | bsdtar -pxf - 2>/dev/null &
cat /tmp/vnfs-checksum | md5sum > /tmp/getvnfs_checksum &

wget -q -O /tmp/vnfs-download http://$master/WW/vnfs?hwaddr=$WWINIT_HWADDR 
```

**Comment by bensallen** [comment]
Closing, will track in PR #37.
