### ISSUE TITLE
Cannot have Duplicate Lines in Array Objects

### ISSUE THREAD

**Issue by bensallen** [warewulf/warewulf3#38]
#12 needs to be able to have duplicate array entries like `mktable gpt`. The code at https://github.com/warewulf/warewulf3/blob/master/common/lib/Warewulf/Object.pm#L252 appears to deduplicate array entries. Can the conditional on line 252, `if (!scalar(grep { $_ eq $newval } @{$self->{$key}}))` be removed? What was the original intention for this?

**Comment by bensallen** [comment]
@gmkurtzer @jmstover Any ideas on this one?

**Comment by jmstover** [comment]
The only think I can think of for duplicates (I think mej would need to be asked...), is that it could make the lookup table more of a mess:

```
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `object_id` int(10) unsigned DEFAULT NULL,
  `field` varchar(64) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `value` varchar(64) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
```

So... it _may_ overwrite, depending on how the update/insert does it, if the there's duplicates... Which wouldn't be what was expected.

Though, I don't believe what you're looking at (file system) is added into the lookup table.

**Comment by bensallen** [comment]
Appears that the filesystem (FS) array ends up in the binstore table.

**Comment by jmstover** [comment]
Right... should be stored on the serialized node object.

I don't know if changing it to allow duplicates will have a unforeseen effect on the behavior of other parts. I just used the lookup table as an example where add removing duplicates would have an effect on those keys depending on how they're added/updated.

**Comment by bensallen** [comment]
#41 closes this issue.

**Comment by gmkurtzer** [comment]
Sorry, late to the party on this but the only thing I would mention is that the filesystem (FS) array should not end up in the binstore as it is stored as an object member (e.g. object dump... will show it).
