### ISSUE TITLE
Hang on getting VNFS for multiple nodes

### ISSUE THREAD

**Issue by macdems** [warewulf/warewulf3#39]
When I make a new VNFS and reboot multiple node at the same time (`wwsh ssh cn[1-6] reboot`) the provisioning process hangs on all nodes but one on wwgetvnfs. The Apache log says:

    ERROR:  Can't open VNFS cache. Locked by another request.
    ERROR:  VNFS is being cached via a different request, try again.

and the provisioned node gets "503 Service Unavailable" and hangs.

**Comment by macdems** [comment]
A workaround seems to be:

    wwsh object modify -s NOCACHE=1 vnfs_name

but this does not resolve the issue.

**Comment by jmstover** [comment]
Hi Maciej

  This is, mostly, expected behavior. It shouldn't hang... but all but the
first node should go into a wait state and try accessing the VNFS later.
Once the VNFS is cached, the lock file is removed.

  The NOCACHE option bypasses the normal cache method and pulls the VNFS
from the database directly instead of a file on disk.

-J

**Comment by macdems** [comment]
Ok, I can imagine this is how it should be. However, `wwgetvnfs` hangs while it should try over and over. My rough guess is that wget does not close `/tmp/vnfs-download` queue if it gets 503 and the unpacking command keeps running. Then the script hangs on the `wait` directive. But as I said, this is just a guess...

**Comment by bensallen** [comment]
@macdems You are spot on. I'll push a fix to #37 and development sometime today. As an aside, I wish there was a better HTTP status code than 503 to use here. Perhaps 423 Locked?

**Comment by macdems** [comment]
As this is rather critical I kindly ask to consider fixing it and adding to master before the 3.7 release. A couple of days ago I have deployed the current master on our research cluster, so I strongly need it to be reliable. For now I will stay with NOCACHE, but I don't know if it won't cause other issues.

**Comment by bensallen** [comment]
Agreed we'll apply this to master as a hot fix after review.

**Comment by macdems** [comment]
I confirm that my tests show that the hotfix works. :+1:

**Comment by bensallen** [comment]
@macdems Thanks for testing.
