### ISSUE TITLE
Update packaging for new database modules

### ISSUE THREAD

**Issue by bensallen** [warewulf/warewulf3#49]
Split out the new MySQL, PG, and Sqlite modules under common/lib/Warewulf/DataStore/SQL from #15 into sub packages in provision RPM spec file, each requiring the appropriate Perl DBD module. This will let sites install the appropriate database backend, and not have to install extra dependancies for databases they're not using.

**Comment by macdems** [comment]
I wonder if this is a proper way in DEB packages. I would rather keep all the modules in the `warewulf-common` package and add at-least-one-of dependency:

    Depends: libdbd-mysql-perl | libdbd-pg-perl | libdbd-sqlite3-perl

**Comment by bensallen** [comment]
@macdems Would we then enforce the correct package be installed in wwinit or somewhere else? 

In general, I prefer package dependancies be dealt with at package install time instead of run time of the application. I'm also leery of using separate methodology for package dependancies between DEBs and RPMs.

Unrelated, we also need to figure out what todo with the warewulf-common-localdb RPM. This is a meta package (ie. no actual files) which via dependancies installs MariaDB/MySQL. Do we rename this to have MySQL in the package name, or leave it as is? Do we implement one for Postgres as well?
