### ISSUE TITLE
wwinit database: Access denied to wwroot

### ISSUE THREAD

**Issue by rengolin** [warewulf/warewulf3#64]
While setting up the master node (replacing OHPC's warewulf packages with the tip of the development branch), following OpenHPC 1.3.1's documentation [1], I got this error:
```
$ wwinit database
database:     Checking to see if RPM 'mysql-server' is installed             NO
database:     Checking to see if RPM 'mariadb-server' is installed           OK
database:     Activating Systemd service: mariadb
database:      + /bin/systemctl -q enable mariadb.service                    OK
database:      + /bin/systemctl -q restart mariadb.service                   OK
database:      + mysqladmin --defaults-extra-file=/tmp/0.kNbSUY5Ku2dI/my.cnf OK
database:     Database version: UNDEF (need to create database)
database:      + mysql --defaults-extra-file=/tmp/0.kNbSUY5Ku2dI/my.cnf ware OK
database:      + mysql --defaults-extra-file=/tmp/0.kNbSUY5Ku2dI/my.cnf ware OK
database:      + mysql --defaults-extra-file=/tmp/0.kNbSUY5Ku2dI/my.cnf ware OK
database:     Checking binstore kindDBI connect('database=warewulf;host=localhost','wwroot',...) failed: Access denied for user 'wwroot'@'localhost' (using password: YES) at /usr/share/perl5/vendor_perl/Warewulf/DataStore/SQL/MySQL.pm line 254.
                                                                        SUCCESS
```
To make sure it was reproducible, I have wiped the machine, PXE installed a fresh CentOS and re-ran my own scripts [2] (based on OHPC's document/scripts).

I'm not sure why `wwinit` is considering that a success. If I run `wwinit database` again, I get the same error, but the database version is set to `1`, which means some of the data was pushed correctly.

Upon close inspection, the only table with any content is `meta` with the dbversion, and the `wwuser` was added to the `mysql::user` table, so I'm not sure what's wrong here.

Changing the user to `root` in `/etc/warewulf/database-root.conf` makes the error disappear. However, the behaviour is still the same, as far as I can tell.

[1] http://www.openhpc.community/downloads/
[2] https://git.linaro.org/leg/hpc/ohpc-scripts.git/

**Comment by bensallen** [comment]
This should be fixed in #61. Primary cause was a typo in the GRANT statement for the wwroot user. As an aside for the work you're doing, you'll also need #62 and #63.

**Comment by rengolin** [comment]
Thanks! I've added a comment to #63 but all of them look ok to me.

**Comment by bensallen** [comment]
@rengolin let us know if #61 fixed this issue.

**Comment by rengolin** [comment]
Rebuilding...

**Comment by rengolin** [comment]
It's working fine now, thanks!
