### ISSUE TITLE
Backport Compressed Kernel Module support in 3.7 to support RHEL/CentOS 7.4

### ISSUE THREAD

**Issue by rajil** [warewulf/warewulf3#79]
@koomie @bensallen @jmstover Centos-7.4 support is presently broken in current stable OHPC. Stateful partitioning is partially broken. It seems that these fixes need to be back ported, https://github.com/warewulf/warewulf3/pull/48 and https://github.com/warewulf/warewulf3/pull/51.

**Comment by bensallen** [comment]
Removing OHPC from issue title as we aren't responsible for what OHPC does. Updating title to be "Backport Compressed Kernel Module support in 3.7 to support RHEL/CentOS 7.4"

**Comment by bensallen** [comment]
@jmstover Let me know what you think about cherry picking the commits in #48 and #51 to master. They seem trivial enough and no new features.

@koomie Will OHPC be able to update its Warewulf release to support RHEL/CentOS 7.4's kernel if we backport these changes?

**Comment by jmstover** [comment]
@bensallen They look good to me. I don't see an issue with it.

**Comment by koomie** [comment]
@jmstover - yes, we can schedule pulling in these changes for the next ohpc release.

**Comment by rajil** [comment]
@koomie What package in OHPC is the file (provision/initramfs/detect) referenced in https://github.com/warewulf/warewulf3/pull/51?

**Comment by jmstover** [comment]
It should be in warewulf-provision IIRC. Maybe, ohpc-warewulf-provision??

-J

**Comment by bensallen** [comment]
@rajil yea should be warewulf-provision. You'll also need to run `wwsh bootstrap rebuild` after upgrading the RPM to pickup the changes.

**Comment by rajil** [comment]
I dont have the 'detect' file installed.

```
$ yum list installed|grep warewulf
ohpc-warewulf.x86_64                   1.3.2-53.1               @OpenHPC-updates
warewulf-cluster-ohpc.x86_64           3.7pre-24.1              @OpenHPC
warewulf-common-ohpc.x86_64            3.7pre-38.1              @OpenHPC-updates
warewulf-provision-ohpc.x86_64         3.7pre-78.1              @OpenHPC-updates
warewulf-provision-server-ohpc.x86_64  3.7pre-78.1              @OpenHPC-updates
warewulf-vnfs-ohpc.x86_64              3.7pre-44.1              @OpenHPC-updates

$ rpm -ql warewulf-provision-ohpc.x86_64|grep detect
$ rpm -ql warewulf-provision-server-ohpc.x86_64|grep detect
```

**Comment by koomie** [comment]
in ohpc, the package name is `warewulf-provision-ohpc`; if you wanted to tweak the build from the last ohpc release, the src rpm is at: http://build.openhpc.community/OpenHPC:/1.3:/Update2:/Factory/CentOS_7/src/warewulf-provision-ohpc-3.7pre-78.1.src.rpm

**Comment by jmstover** [comment]
It's part of the "base" capability. It isn't a stand alone file.

-J

**Comment by rajil** [comment]
@koomie I tweaked the build to include the patches and installed it. My /usr/bin/wwbootstrap did not change though and it seems that this provided by warewulf-vnfs-ohpc-3.7pre-38.1.x86_64. 

Building warewulf-provision.spec didnot give that package,
```
x86_64]# ls -1
warewulf-provision-gpl_sources-ohpc-3.7pre-79.1.x86_64.rpm
warewulf-provision-ohpc-3.7pre-79.1.x86_64.rpm
warewulf-provision-server-ohpc-3.7pre-79.1.x86_64.rpm
```
Do i need to build warewulf-vnfs-ohpc as well?
