### ISSUE TITLE
Consider using snponly.efi instead of ipxe.efi for UEFI boot

### ISSUE THREAD

**Issue by jabl** [warewulf/warewulf3#84]
ipxe.efi uses the iPXE network card drivers; at least Dell PowerEdge Haswell NIC's don't work correctly with it in our testing. snponly.efi is the UEFI equivalent of undionly.kpxe for legacy BIOS, and uses the builtin NIC driver and replaces only the "upper" part of the PXE driver stack. Which seems to work.

**Comment by bensallen** [comment]
Did you try testing with snp.efi? It seems like a more universal build compared to snponly.efi.

```
snp same as snponly but tries to boot all devices and not just the one it was chained via, this is also included in ipxe builds
```

Ref: http://ipxe.org/appnote/buildtargets

**Comment by jabl** [comment]
Hmm, sounds reasonable; I wasn't aware of snp.efi. I'll test it and report back (probably won't have time until next week, unfortunately).

**Comment by jabl** [comment]
Yes, I confirm it works with snp.efi as well.

For completess, the product name of the tested system was Dell PowerEdge C6320, and lspci tells that the onboard NIC's are of type:

Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)

**Comment by bensallen** [comment]
@jabl Thanks for testing. I'll update this when I find some time.

**Comment by bensallen** [comment]
Fixed in #90.

**Comment by yiya1989** [comment]
Is the snp.efi more similar to undionly.kpxe? why not the snponly.efi ? When I use the ipxe, i mostly what to  boot the specific NIC device it was chained from. @bensallen

**Comment by bensallen** [comment]
@yiya1989 See http://ipxe.org/appnote/buildtargets. "snp same as snponly but tries to boot all devices and not just the one it was chained via, this is also included in ipxe builds"

This logic matches our approach in the Warewulf initramfs so it was preferred.
