### ISSUE TITLE
"wwsh pxe update" is issuing a return code of 1

### ISSUE THREAD

**Issue by PaulUTK** [warewulf/warewulf3#94]
I'm implementing a set of ansible plays to implement an openHPC installation and I found that when I run wwsh pxe update it returns 1.

[root@ww-master ~]# wwsh pxe update
[root@ww-master ~]# echo $?
1

Turning on debug reveals nothing helpful either other than it is returning 1.

[Warewulf::Provision::Pxe->update()/250]:  Creating a pxe config for node 'ww2-eth0/00:0a:aa:aa:aa:02'
Building iPXE configuration for: ww2/00:0a:aa:aa:aa:02
[Warewulf::Provision::Pxe->update()/267]:  Creating iPXE config at: /srv/warewulf/ipxe/cfg/00:0a:aa:aa:aa:02
[Warewulf::Provision::Pxe->update()/307]:  ww2: Skipping static gateway configuration as it is unconfigured
[Warewulf::Provision::Pxe->update()/312]:  ww2: Skipping static MTU configuration as it is unconfigured
[wwsh->run_cmd()/61]:                   Command executed by 1 modules with return code 1
[Warewulf::EventHandler->handle()/204]:  No events registered for: WWSH.END
[Warewulf::EventHandler->handle()/225]:  No events registered for: WWSH.*
[Warewulf::EventHandler->handle()/243]:  No events registered for: *.END

After adding some debug and tracking down the issue, it appears as if the pxe update call is returning an undef value to wwsh which is then causing retval to be incremented.

https://github.com/warewulf/warewulf3/blob/963db917add5ca647cb9c1641005911a1a63b3ba/common/bin/wwsh#L47

This is the module returning 1 "Warewulf::Module::Cli::Pxe=HASH(0x2a8f698)->exec(update)
".

At the very least adding a return TRUE once the update module completes will get past this problem, but it isn't the fully developed solution of course.

https://github.com/warewulf/warewulf3/blob/963db917add5ca647cb9c1641005911a1a63b3ba/provision/lib/Warewulf/Provision/Pxe.pm#L131

And also possibly a return in front of this line.

https://github.com/warewulf/warewulf3/blob/963db917add5ca647cb9c1641005911a1a63b3ba/provision/lib/Warewulf/Module/Cli/Pxe.pm#L122

return $pxe->update($objSet->get_list());

Thanks,

Paul

**Comment by bensallen** [comment]
Hey Paul, are you using OpenHPC's distribution of Warewulf, or a build off of the Github master or development branch?

**Comment by PaulUTK** [comment]
OpenHPC distribution of it.

[root@ww-master ~]# rpm -q --whatprovides /usr/bin/wwsh
warewulf-common-ohpc-3.8pre-11.1.x86_64

**Comment by bensallen** [comment]
#95 should close this. Let me know if you run into issues with it.
